FROM python:3.6.4

# install environment dependencies
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    netcat \
  && apt-get -q clean

# set working directory
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# add app
COPY . .

# run server
RUN chmod 777 entrypoint.sh

# run server
CMD ["/usr/src/app/entrypoint-prod.sh"]
